#include <linux/loop.h>

#define LOOPIO_MAGIC 'L'

#define LOOPIO_SET_FD (0xFF & LOOP_SET_FD)
#define LOOPIO_CLR_FD (0xFF & LOOP_CLR_FD)
#define LOOPIO_SET_STATUS (0xFF & LOOP_SET_STATUS)
#define LOOPIO_GET_STATUS (0xFF & LOOP_GET_STATUS)
#define LOOPIO_SET_STATUS64 (0xFF & LOOP_SET_STATUS64)
#define LOOPIO_GET_STATUS64 (0xFF & LOOP_GET_STATUS64)
#define LOOPIO_CHANGE_FD (0xFF & LOOP_CHANGE_FD)
#define LOOPIO_SET_CAPACITY (0xFF & LOOP_SET_CAPACITY)
#define LOOPIO_SET_DIRECT_IO (0xFF & LOOP_SET_DIRECT_IO)
#define LOOPIO_SET_BLOCK_SIZE (0xFF & LOOP_SET_BLOCK_SIZE)
#define LOOPIO_CONFIGURE (0xFF & LOOP_CONFIGURE)

#define LOOPCTL_ADD (0xFF & LOOP_CTL_ADD)
#define LOOPCTL_REMOVE (0xFF & LOOP_CTL_REMOVE)
#define LOOPCTL_GET_FREE (0xFF & LOOP_CTL_GET_FREE)